# esto es independiente a bungeecord
# para utilizar placeholder de estos servidores usa
# {lobby_players}
# {lobby_motd}
# {lobby_maxplayers}
# tiempo en milisegundos
Modules:
  Inventory:
    syncDatabase: 5 #Sincronización en segundos
Vars: #Variables con formula (+) el cual te permitirá hacer un solo conteo de varias conexiones
  global_lobby: # este nombre es el que se reemplazará {global_lobby} y obtendras el singular y plural segun sea correspondiente
    formula: 'lobby+lobby1'
    singular: '{0} Jugador' # el estado de cuando la formula sea singular retornará esto
    plural: '{0} Jugadores' # el estado de cuando la formula sea plural retornará esto
syncDelay: 1500 #Sincronización de conexiónes para retornar datos de las conexiónes
SkinFetcher: external
Connections:
  lobby:
    host: "localhost:25566"