Redis:
  Host: 'localhost'
  PassWord: 'LKJqwjsaLkS'
  Port: 6379
MySQL:
  Enable: false
  Host: 'localhost:3306'
  UserName: root
  PassWord: ''
  DatabaseName: 'mcdb'
  PoolSize: 20
  TimeOut: 30000
  Modules:
    Inventory:
      TableName: 'inventories'
    NPC:
      TableName: 'npcserver'
      PlayerStats:
        TableName: 'playerstatsnpc'
    Scoreboard:
      TableName: 'scoreboardserver'
    Cooldown:
      TableName: 'cooldownserver'